"""Parity tests: Python slug helpers must match the TypeScript output in
web/lib/seo.ts for every shape we observe in production.

The expected values below were generated by running the TS helpers
verbatim under Node — see scripts/regen_slug_fixtures.md.

Hardware has one intentional divergence: the Python helper strips the
"+ CPU + RAM" tail of an accelerator_summary so the MCP server can route
free-text user input ("RTX 5090") to the same hardware bucket. The
website does not need this because /hw routes come from a curated
catalog. The divergent case is asserted explicitly.
"""

from __future__ import annotations

import pytest

from cli.mcp.slugs import (
    canonical_hardware_slug,
    canonical_model_slug,
    clean_model_display_name,
)


# Cases where Python output must equal TypeScript output.
MODEL_PARITY_CASES: list[tuple[str | None, str]] = [
    ("mlx-community/Qwen2.5-7B-Instruct-4bit", "qwen2-5-7b-instruct"),
    ("mlx-community-Qwen2.5-0.5B-Instruct-4bit", "qwen2-5-0-5b-instruct"),
    ("meta-llama/llama-3.3-70b-instruct", "llama-3-3-70b-instruct"),
    ("anthropic/claude-haiku-4.5", "claude-haiku-4-5"),
    ("Qwen/Qwen3-Coder-Next", "qwen3-coder-next"),
    ("Qwen3.6-27B-Q4_K_M.gguf", "qwen3-6-27b-q4-k-m"),
    ("mlx-community/gpt-oss-20b-MXFP4-Q4", "gpt-oss-20b"),
    ("mlx-community/llama-3.3-70b-Instruct-4bit", "llama-3-3-70b-instruct"),
    ("openai/gpt-4o-mini", "gpt-4o-mini"),
    (None, ""),
    ("", ""),
]


# Hardware cases that must round-trip identically (no "+ CPU + RAM" tail).
HARDWARE_PARITY_CASES: list[tuple[str | None, str]] = [
    ("RTX 5090 (32GB)", "rtx-5090"),
    ("M3 Ultra (192GB)", "m3-ultra"),
    ("H100 SXM (80GB)", "h100-sxm"),
    ("RTX 4090 (24GB Aorus OC)", "rtx-4090"),
    (None, ""),
    ("", ""),
]


@pytest.mark.parametrize("name, expected", MODEL_PARITY_CASES)
def test_canonical_model_slug_parity(name: str | None, expected: str) -> None:
    assert canonical_model_slug(name) == expected


@pytest.mark.parametrize("label, expected", HARDWARE_PARITY_CASES)
def test_canonical_hardware_slug_parity(label: str | None, expected: str) -> None:
    assert canonical_hardware_slug(label) == expected


def test_hardware_strips_cpu_ram_tail_mcp_only() -> None:
    # Documented divergence: the MCP server collapses "GPU + CPU + RAM"
    # accelerator summaries to just the GPU. The website slug for the
    # same label would be "m3-pro-36gb-unified" (catalog-curated). The
    # MCP must dedupe across CPU/RAM variants of the same accelerator.
    label = "M3 Pro (18-core GPU) + 36GB unified"
    assert canonical_hardware_slug(label) == "m3-pro"

    # Same accelerator, different CPU/RAM tail → same MCP bucket.
    a = "RTX 5090 (32GB) + AMD Ryzen 7 9850X3D 8-Core Processor (8c) + 30GB"
    b = "RTX 5090 (32GB) + AMD64 Family 26 Model 68 Stepping 0, AuthenticAMD (8c) + 62GB"
    assert canonical_hardware_slug(a) == canonical_hardware_slug(b) == "rtx-5090"


def test_clean_model_display_name() -> None:
    assert clean_model_display_name("mlx-community/Qwen2.5-7B-Instruct") == "Qwen2.5-7B-Instruct"
    assert clean_model_display_name("anthropic/claude-haiku-4.5") == "claude-haiku-4.5"
    assert clean_model_display_name("Qwen3-Coder-Next") == "Qwen3-Coder-Next"
    assert clean_model_display_name(None) == ""
    assert clean_model_display_name("") == ""
